Proposed Cleanup, Optimizations & Prep for Multi-controller
PlaidSystems/Spruce-Hubitat pull request #1
Opened 2019-12-12 19:59 UTC by SANdood

Nate (et al) -

Here are some proposed updates for the base Hubitat code. Most changes are noted within each module, but the overview is this:
1) Spruce Control now creates all devices with more descriptive device Labels - e.g. "Spruce Lawn Controller" instead of just "Lawn"; "Spruce Lawn Controller Zone 01" instead of "Zone 01", etc.
  - this includes the "Spruce Pause" child device(s) which are now labelled "Spruce Lawn Controller Pause". This change necessitated changing the Spruce wifi master to use the actual deviceNetworkId of the Pause device instead of its name/label when referencing the device. The deviceNetworkId is stored as a state variable when the Pause device is created.
2. For the sensors, the code has been refactored for the Hubitat environment in 3 ways:
  - Instead of entering a temperature offset, ALL Hubitat temperature devices use the "Enter current reference temperature reading" approach, and calculate the offset automatically from this data point;
  - Added conditionals for log.debug and log.info logging (logging is a large overhead on Hubitat). Both are enabled by default, but in keeping with Hubitat standards, the debug logging is disabled after 1 hour (usually it is only 30 minutes, but these devices are really lazy 😄)
  - added the `importUrl definition in the device metadata section
3. Various optimizations, like increased decimal precision and ROUND_HALF_UP instead of Math.round

I will likely have more updates to offer over time, as I am working towards a version that natively supports multiple controllers instead of the current limitation of only 1 controller per Hub. Users of multiple Hubitat Hubs linked via HubConnect can get around the limitations fairly easily, and I will be releasing Custom Drivers that help make that a reality for people. But ultimately, the system should readily support multiple controllers, although it will take a bit more work to make that a reality.

2019-12-12 22:02 UTC, SANdood commented
Removed debug code "refreshAttributes()"

2019-12-13 18:42 UTC, natec007 commented
Looks like some nice improvements, I'll check/test on our end.

2019-12-13 19:18 UTC, SANdood commented
Nate -

Thanks!

I'm still working on skipping duplicate humidity events in Spruce Sensor - seems a rampant problem on Hubitat.

The version posted will never resend a humidity update if the value never changes. My working version only skips repeated events within the last 10 seconds (generally the worst case scenario is 2-3 duplicates separated by about 2 seconds). There's no harm in duplicates, but they do add system overhead...

> On Dec 13, 2019, at 1:42 PM, natec007 <notifications@github.com> wrote:
> 
> Looks like some nice improvements, I'll check/test on our end.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/PlaidSystems/Spruce-Hubitat/pull/1?email_source=notifications&email_token=AB5FQUFQEOAZCTGWS4VNI73QYPJQBA5CNFSM4J2DVER2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEG24AZY#issuecomment-565559399>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AB5FQUDITJXXSS335AMOH53QYPJQBANCNFSM4J2DVERQ>.
>

2019-12-15 11:47 UTC, SANdood commented
This update simplifies the "ignore duplicates" code in Spruce Sensor, and adds a new *setInterval()* command to make it possible to update the measurement interval on the sensor programmatically.  I envision a RM rule that sets the interval of my far-away sensors to hourly after that schedule has run (or started), then resets it to 10 minutes before the Schedules look at the sensors in preparation for the next cycle. Possibly this will improve battery life of my sensors...

2019-12-16 13:58 UTC, SANdood commented
Added `setInterval()` command, so you can set a longer interval during periods that the sensors aren't being queried for a Sensor Schedule...

2020-05-16 04:07 UTC, natec007 commented on apps/Spruce Connect.src
> +		String controllerName = settings.controller.displayName
I see error displayName does not exist.  settings.controller should be all that is needed.  Error is causing schedule and pause child devices not to populate

2020-05-16 04:32 UTC, natec007 requested changes
Hey Barry,
Did you have any new updates you wanted to add?  I have the 3 files in test and only saw the 1 error.
thanks

2020-05-16 10:01 UTC, SANdood commented
Added fixes for sensor name change

2020-06-02 14:11 UTC, SANdood commented
This is the last set of major updates, and includes all the stuff we have discussed via email:
- Added http timeouts
- No longer deletes all child devices when Access Token is lost/regenerated
- Existing devices (by deviceNetworkId) are renamed instead of deleted/re-added 
  - included Controllers, Zones, Schedules and Pause device
- After all devices (as defined by Spruce Cloud) are created/renamed, unused devices are deleted
- After install or update, all Sensor states are updated (after a 30 second delay)
- Debug/Info logging cleaned up

2020-06-13 21:04 UTC, natec007 approved these changes

2020-06-13 21:04 UTC, merged

2020-06-13 21:06 UTC, natec007 commented
Thanks Barry!
The updates are a HUGE improvement!!